var list1 = [
{list:"1",
id:"D3",
idcontext:"D3-C1",
condition:"Context1",
predicate:"discover",
name1:"Rachel",
name2:"Don",
context:"What about Don? Is he American?",
target:"Perhaps Rachel discovered that he\'s Canadian.",
prompt:"Don is Canadian",
denial:"No, he\'s not Canadian."},
 {list:"1",
id:"F",
idcontext:"F2",
condition:"Filler",
predicate:"none",
name1:"Leah",
name2:"none",
context:"What about Leah? Was she there?",
target:"She was invited to the party.",
prompt:"Leah was invited to the party",
denial:"No, she wasn\'t invited."},
 {list:"1",
id:"A2",
idcontext:"A2-C1",
condition:"Context1",
predicate:"be aware",
name1:"Erin",
name2:"Simon",
context:"What about Simon? Is he dependable?",
target:"Perhaps Erin was aware that he\'s unreliable.",
prompt:"Simon is unreliable",
denial:"No, he\'s isn\'t unreliable."},
 {list:"1",
id:"K2",
idcontext:"K2-C2",
condition:"Context2",
predicate:"know",
name1:"Daniel",
name2:"Cindy",
context:"What about Daniel? Why was he disappointed?",
target:"Perhaps he knew that Cindy was married.",
prompt:"Cindy was married",
denial:"No, she wasn\'t married."},
 {list:"1",
id:"A3",
idcontext:"A3-C2",
condition:"Context2",
predicate:"be aware",
name1:"Chelsea",
name2:"Robert",
context:"What about Chelsea? Why did she reject his application?",
target:"Perhaps she was aware that Robert had bad reviews.",
prompt:"Robert had bad reviews",
denial:"No, he didn\'t have bad reviews."},
 {list:"1",
id:"A1",
idcontext:"A1-C2",
condition:"Context2",
predicate:"be aware",
name1:"Martha",
name2:"William",
context:"What about Martha? Why did she serve tofu?",
target:"Perhaps she was aware that William\'s a vegetarian.",
prompt:"William is a vegetarian",
denial:"No, he\'s not a vegetarian."},
 {list:"1",
id:"R3",
idcontext:"R3-C2",
condition:"Context2",
predicate:"realize",
name1:"Evan",
name2:"Megan",
context:"What about Evan? Why was he angry?",
target:"Perhaps he realized that Megan was cheating on him.",
prompt:"Megan was cheating on Evan",
denial:"No, she wasn\'t cheating on him."},
 {list:"1",
id:"N2",
idcontext:"N2-C2",
condition:"Context2",
predicate:"notice",
name1:"Jessica",
name2:"David",
context:"What about Jessica? Why did she walk away? ",
target:"Perhaps she noticed that David had bad breath.",
prompt:"David had bad breath",
denial:"No, he didn\'t have bad breath."},
 {list:"1",
id:"D2",
idcontext:"D2-C2",
condition:"Context2",
predicate:"discover",
name1:"Alice",
name2:"John",
context:"What about Alice? Why was she upset?",
target:"Perhaps she discovered that John\'s a father.",
prompt:"John is a father",
denial:"No, he\'s not a father."},
 {list:"1",
id:"K3",
idcontext:"K3-C1",
condition:"Context1",
predicate:"know",
name1:"Rhonda",
name2:"Bill",
context:"What about Bill? Was he correct?",
target:"Perhaps Rhonda knew that he was wrong.",
prompt:"Bill was wrong",
denial:"No, he wasn\'t wrong."},
 {list:"1",
id:"D1",
idcontext:"D1-C1",
condition:"Context1",
predicate:"discover",
name1:"Josh",
name2:"Lisa",
context:"What about Lisa? Is she married?",
target:"Perhaps Josh discovered that she\'s a widow.",
prompt:"Lisa is a widow",
denial:"No, she\'s not a widow."},
 {list:"1",
id:"N3",
idcontext:"N3-C1",
condition:"Context1",
predicate:"notice",
name1:"Steven",
name2:"Gina",
context:"What about Gina? Was she full from lunch?",
target:"Perhaps Steven noticed that she was hungry.",
prompt:"Gina was hungry",
denial:"No, she wasn\'t hungry."},
 {list:"1",
id:"F",
idcontext:"F1",
condition:"Filler",
predicate:"none",
name1:"Ronald",
name2:"none",
context:"What about Ronald? Was he feeling well?",
target:"He was tired.",
prompt:"Ronald was tired",
denial:"No, he wasn\'t tired."},
 {list:"1",
id:"K1",
idcontext:"K1-C1",
condition:"Context1",
predicate:"know",
name1:"Linda",
name2:"Andy",
context:"What about Andy? Was he innocent?",
target:"Perhaps Linda knew that he was a criminal.",
prompt:"Andy was a criminal",
denial:"No, he\'s not a criminal."},
 {list:"1",
id:"R1",
idcontext:"R1-C2",
condition:"Context2",
predicate:"realize",
name1:"Bob",
name2:"Mary",
context:"What about Bob? Why did he refuse to pay?",
target:"Perhaps he realized that Mary\'s wealthy.",
prompt:"Mary is wealthy",
denial:"No, she\'s not wealthy."},
 {list:"1",
id:"N1",
idcontext:"N1-C1",
condition:"Context1",
predicate:"notice",
name1:"Ryan",
name2:"Lily",
context:"What about Lily? Did she have everything?",
target:"Perhaps Ryan noticed that she was missing something.",
prompt:"Lily was missing something",
denial:"No, she wasn\'t missing anything."},
 {list:"1",
id:"R2",
idcontext:"R2-C1",
condition:"Context1",
predicate:"realize",
name1:"Sarah",
name2:"Cory",
context:"What about Cory? Was he healthy?",
target:"Perhaps Sarah realized that he had a virus.",
prompt:"Cory had a virus",
denial:"No, he didn\'t have a virus."}
];

var list2 = [
{list:"2",
id:"K2",
idcontext:"K2-C1",
condition:"Context1",
predicate:"know",
name1:"Daniel",
name2:"Cindy",
context:"What about Cindy? Was she single?",
target:"Perhaps Daniel knew that she was married.",
prompt:"Cindy was married",
denial:"No, she wasn\'t married."},
 {list:"2",
id:"N1",
idcontext:"N1-C2",
condition:"Context2",
predicate:"notice",
name1:"Ryan",
name2:"Lily",
context:"What about Ryan? Why did he sigh?",
target:"Perhaps he noticed that Lily was missing something.",
prompt:"Lily was missing something",
denial:"No, she wasn\'t missing anything."},
 {list:"2",
id:"A3",
idcontext:"A3-C1",
condition:"Context1",
predicate:"be aware",
name1:"Chelsea",
name2:"Robert",
context:"What about Robert? Did he have a good reputation?",
target:"Perhaps Chelsea was aware that he had bad reviews.",
prompt:"Robert had bad reviews",
denial:"No, he didn\'t have bad reviews."},
 {list:"2",
id:"K3",
idcontext:"K3-C2",
condition:"Context2",
predicate:"know",
name1:"Rhonda",
name2:"Bill",
context:"What about Rhonda? Why was she irritated?",
target:"Perhaps she knew that Bill was wrong.",
prompt:"Bill was wrong",
denial:"No, he wasn\'t wrong."},
 {list:"2",
id:"D3",
idcontext:"D3-C2",
condition:"Context2",
predicate:"discover",
name1:"Rachel",
name2:"Don",
context:"What about Rachel? Why did she bring maple syrup?",
target:"Perhaps she discovered that Don\'s Canadian.",
prompt:"Don is Canadian",
denial:"No, he\'s not Canadian."},
 {list:"2",
id:"A2",
idcontext:"A2-C2",
condition:"Context2",
predicate:"be aware",
name1:"Erin",
name2:"Simon",
context:"What about Erin? Why did she do it herself?",
target:"Perhaps she was aware that Simon\'s unreliable.",
prompt:"Simon is unreliable",
denial:"No, he isn\'t unreliable."},
 {list:"2",
id:"R3",
idcontext:"R3-C1",
condition:"Context1",
predicate:"realize",
name1:"Evan",
name2:"Megan",
context:"What about Megan? Was she faithful?",
target:"Perhaps Evan realized that she was cheating on him.",
prompt:"Megan was cheating on Evan",
denial:"No, she wasn\'t cheating on him."},
 {list:"2",
id:"R2",
idcontext:"R2-C2",
condition:"Context2",
predicate:"realize",
name1:"Sarah",
name2:"Cory",
context:"What about Sarah? Why was she concerned?",
target:"Perhaps she realized that Cory had a virus.",
prompt:"Cory had a virus",
denial:"No, he didn\'t have a virus."},
 {list:"2",
id:"N3",
idcontext:"N3-C2",
condition:"Context2",
predicate:"notice",
name1:"Steven",
name2:"Gina",
context:"What about Steven? Why did he bring sandwiches?",
target:"Perhaps he noticed that Gina was hungry.",
prompt:"Gina was hungry",
denial:"No, she wasn\'t hungry."},
 {list:"2",
id:"K1",
idcontext:"K1-C2",
condition:"Context2",
predicate:"know",
name1:"Linda",
name2:"Andy",
context:"What about Linda? Why was she worried?",
target:"Perhaps she knew that Andy was a criminal.",
prompt:"Andy was a criminal",
denial:"No, he\'s not a criminal."},
 {list:"2",
id:"D2",
idcontext:"D2-C1",
condition:"Context1",
predicate:"discover",
name1:"Alice",
name2:"John",
context:"What about John? Is he a bachelor? ",
target:"Perhaps Alice discovered that he\'s a father.",
prompt:"John is a father",
denial:"No, he\'s not a father."},
 {list:"2",
id:"D1",
idcontext:"D1-C2",
condition:"Context2",
predicate:"discover",
name1:"Josh",
name2:"Lisa",
context:"What about Josh? Why did he smile?",
target:"Perhaps he discovered that Lisa\'s a widow.",
prompt:"Lisa is a widow",
denial:"No, she\'s not a widow."},
 {list:"2",
id:"F",
idcontext:"F2",
condition:"Filler",
predicate:"none",
name1:"Leah",
name2:"none",
context:"What about Leah? Was she there?",
target:"She was invited to the party.",
prompt:"Leah was invited to the party",
denial:"No, she wasn\'t invited."},
 {list:"2",
id:"F",
idcontext:"F1",
condition:"Filler",
predicate:"none",
name1:"Ronald",
name2:"none",
context:"What about Ronald? Was he feeling well?",
target:"He was tired.",
prompt:"Ronald was tired",
denial:"No, he wasn\'t tired."},
 {list:"2",
id:"A1",
idcontext:"A1-C1",
condition:"Context1",
predicate:"be aware",
name1:"Martha",
name2:"William",
context:"What about William? Does he eat meat?",
target:"Perhaps Martha was aware that he\'s a vegetarian.",
prompt:"William is a vegetarian",
denial:"No, he\'s not a vegetarian."},
 {list:"2",
id:"N2",
idcontext:"N2-C1",
condition:"Context1",
predicate:"notice",
name1:"Jessica",
name2:"David",
context:"What about David? Did he have good oral hygiene?",
target:"Perhaps Jessica noticed that he had bad breath.",
prompt:"David had bad breath",
denial:"No, he didn\'t have bad breath."},
 {list:"2",
id:"R1",
idcontext:"R1-C1",
condition:"Context1",
predicate:"realize",
name1:"Bob",
name2:"Mary",
context:"What about Mary? Is she poor?",
target:"Perhaps Bob realized that she\'s wealthy.",
prompt:"Mary is wealthy",
denial:"No, she\'s not wealthy."}
    ];